spring.application.name=Gam
server.port=8080
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/gam?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=${DB_User}
spring.datasource.password=${DB_Password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

jwt.secret=${Jwt_security}
jwt.expiration = 1209600000
jwt.refresh-expiration=1209600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pjsleey12312@gmail.com
spring.mail.password=${Google_Password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

naver.client.id=${Naver_Client}
naver.client.secret=${Naver_security}

kakao.restapi.key=${Kakao_API}

gemini.api.key=${AI_Key}

youtube.api-key=${Youtube_API_Key}

spotify.client-id=${Song_client}
spotify.client-secret=${Song_security}